// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListFreebies():Promise<main.FreebieSnapshot>;

export function MarkFreebieStatus(arg1:string,arg2:string,arg3:string):Promise<main.FreebieSnapshot>;

export function OpenSteamLogin():Promise<void>;

export function OpenSteamSearch():Promise<void>;

export function OpenStorePage(arg1:string):Promise<void>;

export function RefreshFreebies():Promise<main.FreebieSnapshot>;
