// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFreebies() {
  return window['go']['main']['App']['ListFreebies']();
}

export function MarkFreebieStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['MarkFreebieStatus'](arg1, arg2, arg3);
}

export function OpenSteamLogin() {
  return window['go']['main']['App']['OpenSteamLogin']();
}

export function OpenSteamSearch() {
  return window['go']['main']['App']['OpenSteamSearch']();
}

export function OpenStorePage(arg1) {
  return window['go']['main']['App']['OpenStorePage'](arg1);
}

export function RefreshFreebies() {
  return window['go']['main']['App']['RefreshFreebies']();
}
