// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RunDiagnosis(arg1:string):Promise<main.DiagnosisReport>;

export function ScanLocalProxies():Promise<Array<main.ProbeResult>>;

export function TestManualProxy(arg1:string):Promise<main.ProbeResult>;
