// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunDiagnosis(arg1) {
  return window['go']['main']['App']['RunDiagnosis'](arg1);
}

export function ScanLocalProxies() {
  return window['go']['main']['App']['ScanLocalProxies']();
}

export function TestManualProxy(arg1) {
  return window['go']['main']['App']['TestManualProxy'](arg1);
}
