// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSteamLogin(arg1) {
  return window['go']['main']['App']['CancelSteamLogin'](arg1);
}

export function ClaimFreebie(arg1) {
  return window['go']['main']['App']['ClaimFreebie'](arg1);
}

export function GetNetworkConfig() {
  return window['go']['main']['App']['GetNetworkConfig']();
}

export function GetSteamAccount() {
  return window['go']['main']['App']['GetSteamAccount']();
}

export function GetSteamLoginStatus(arg1) {
  return window['go']['main']['App']['GetSteamLoginStatus'](arg1);
}

export function ListFreebies() {
  return window['go']['main']['App']['ListFreebies']();
}

export function LogoutSteam() {
  return window['go']['main']['App']['LogoutSteam']();
}

export function MarkFreebieStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['MarkFreebieStatus'](arg1, arg2, arg3);
}

export function OpenStorePage(arg1) {
  return window['go']['main']['App']['OpenStorePage'](arg1);
}

export function RefreshFreebies() {
  return window['go']['main']['App']['RefreshFreebies']();
}

export function SaveNetworkConfig(arg1) {
  return window['go']['main']['App']['SaveNetworkConfig'](arg1);
}

export function StartSteamCredentialLogin(arg1) {
  return window['go']['main']['App']['StartSteamCredentialLogin'](arg1);
}

export function StartSteamQRLogin() {
  return window['go']['main']['App']['StartSteamQRLogin']();
}

export function SubmitSteamGuardCode(arg1) {
  return window['go']['main']['App']['SubmitSteamGuardCode'](arg1);
}

export function TestWebSession() {
  return window['go']['main']['App']['TestWebSession']();
}
