// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSteamLogin(arg1:string):Promise<void>;

export function ClaimFreebie(arg1:string):Promise<main.FreebieClaimResult>;

export function GetNetworkConfig():Promise<main.NetworkConfig>;

export function GetSteamAccount():Promise<main.SteamAccountSummary>;

export function GetSteamLoginStatus(arg1:string):Promise<main.LoginStatus>;

export function ListFreebies():Promise<main.FreebieSnapshot>;

export function LogoutSteam():Promise<void>;

export function MarkFreebieStatus(arg1:string,arg2:string,arg3:string):Promise<main.FreebieSnapshot>;

export function OpenStorePage(arg1:string):Promise<void>;

export function RefreshFreebies():Promise<main.FreebieSnapshot>;

export function SaveNetworkConfig(arg1:main.NetworkConfigRequest):Promise<main.NetworkConfig>;

export function StartSteamCredentialLogin(arg1:main.CredentialLoginStartRequest):Promise<main.LoginStartResult>;

export function StartSteamQRLogin():Promise<main.QRLoginStartResult>;

export function SubmitSteamGuardCode(arg1:main.SubmitGuardCodeRequest):Promise<void>;

export function TestWebSession():Promise<main.WebSessionTestResult>;
